#ifndef BULL_GRAPHICS_ABSTRACTVIEWER_HPP
#define BULL_GRAPHICS_ABSTRACTVIEWER_HPP

#include <Bull/Graphics/Export.hpp>

#include <Bull/Math/Matrix/Matrix4.hpp>
#include <Bull/Math/Vector/Vector3.hpp>

namespace Bull
{
    struct BULL_GRAPHICS_API AbstractViewer
    {
        /*! \brief Get the up Vector of the Viewer
         *
         * \return The up Vector
         *
         */
        virtual Vector3F getUp() const = 0;

        /*! \brief Get the right vector of the Viewer
         *
         * \return The right vector
         *
         */
        virtual Vector3F getRight() const = 0;

        /*! \brief Get the forward vector of the Viewer
         *
         * \return The forward vector
         *
         */
        virtual Vector3F getForward() const = 0;

        /*! \brief Get the position of the Viewer
         *
         * \return The position
         *
         */
        virtual Vector3F getPosition() const = 0;

        /*! \brief Get the view matrix generated by the Viewer
         *
         * \return The view matrix
         *
         */
        virtual Matrix4F getViewMatrix() const = 0;
    };
}

#endif // BULL_GRAPHICS_ABSTRACTVIEWER_HPP
