#ifndef BULL_NETWORK_SOCKET_WIN32_SOCKETHEADER_HPP
#define BULL_NETWORK_SOCKET_WIN32_SOCKETHEADER_HPP

#include <winsock2.h>
#include <ws2tcpip.h>

#endif // BULL_NETWORK_SOCKET_WIN32_SOCKETHEADER_HPP
