#ifndef BULL_RENDER_CONTEXT_WGL_WGLMULTISAMPLE_HPP
#define BULL_RENDER_CONTEXT_WGL_WGLMULTISAMPLE_HPP

#define WGL_SAMPLE_BUFFERS_ARB 0x2041
#define WGL_SAMPLES_ARB        0x2042

#endif // BULL_RENDER_CONTEXT_WGL_WGLMULTISAMPLE_HPP
