#ifndef BULL_MATH_TRANSFORMATIONPIPELINE_CAMERA_HPP
#define BULL_MATH_TRANSFORMATIONPIPELINE_CAMERA_HPP

#include <Bull/Math/Matrix/Matrix4.hpp>
#include <Bull/Math/Vector/Vector3.hpp>

namespace Bull
{
    template <typename T>
    class Camera
    {
    public:

        /*! \brief Default constructor
         *
         */
        Camera();

        /*! \brief Constructor
         *
         * \param position The initial position of the Camera
         * \param target   The target to look at
         * \param up       The up vector of the Camera
         *
         */
        Camera(const Vector3<T>& position, const Vector3<T>& target, const Vector3<T> up = Vector3<T>::Up);

        /*! \brief Set the Camera's position
         *
         * \param position The position
         *
         * \return This
         *
         */
        Camera<T>& setPosition(const Vector3<T>& position);

        /*! \brief Get the position of the Camera
         *
         * \return The position
         *
         */
        const Vector3<T>& getPosition() const;

        /*! \brief Set the target to look at
         *
         * \param position The position
         *
         * \return This
         *
         */
        Camera<T>& setTarget(const Vector3<T>& target);

        /*! \brief Get the target of the Camera
         *
         * \return The target
         *
         */
        const Vector3<T>& getTarget() const;

        /*! \brief Set the up vector
         *
         * \param position The position
         *
         * \return This
         *
         */
        Camera<T>& setUp(const Vector3<T>& up);

        /*! \brief Get the up vector of the Camera
         *
         * \return The up vector
         *
         */
        const Vector3<T>& getUp() const;

        /*! \brief Get the view matrix generated by the Camera
         *
         * \return The view matrix
         *
         */
        const Matrix4<T>& getMatrix() const;

    private:

        /*! \brief Recompute the view matrix
         *
         */
        void recomputeMatrix();

        Vector3<T> m_up;
        Matrix4<T> m_view;
        Vector3<T> m_target;
        Vector3<T> m_position;
    };

    typedef Camera<int>          CameraI;
    typedef Camera<float>        CameraF;
    typedef Camera<double>       CameraD;
    typedef Camera<unsigned int> CameraUI;
}

#include <Bull/Math/TransformationPipeline/Camera.inl>

#endif //BULL_MATH_TRANSFORMATIONPIPELINE_CAMERA_HPP
