#ifndef BULL_MATH_TRANSFORMATIONPIPELINE_CAMERA_HPP
#define BULL_MATH_TRANSFORMATIONPIPELINE_CAMERA_HPP

#include <Bull/Math/Matrix/Matrix4.hpp>
#include <Bull/Math/Vector/Vector3.hpp>

namespace Bull
{
    template <typename T>
    class Camera
    {
    private:

        /*! \brief Compute lookAt matrix
         *
         * \param eye
         * \param target
         * \param up
         *
         * \return
         *
         */
        static Matrix4<T> lootAt(const Vector3<T>& eye, const Vector3<T>& target, const Vector3<T>& up);

    public:

        /*! \brief Default constructor
         *
         */
        Camera();

        /*! \brief Get the view matrix generated by the Camera
         *
         * \return The view matrix
         *
         */
        const Matrix4<T>& getMatrix() const;

    private:

        /*! \brief Recompute the view matrix
         *
         */
        void recomputeMatrix();

        Matrix4<T> m_view;
    };

    typedef Camera<int>          CameraI;
    typedef Camera<float>        CameraF;
    typedef Camera<double>       CameraD;
    typedef Camera<unsigned int> CameraUI;
}

#include <Bull/Math/TransformationPipeline/Camera.inl>

#endif //BULL_MATH_TRANSFORMATIONPIPELINE_CAMERA_HPP
