if(CMAKE_VERSION VERSION_LESS "3.1")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++14")
    endif()
else()
    set(CMAKE_CXX_STANDARD 14)
endif()

set(CMAKE_CXX_FLAGS "-Bstatic")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "bin/${CMAKE_BUILD_TYPE}")

set(BULL_ROOT ${CMAKE_CURRENT_SOURCE_DIR})

set(CMAKE_MAJOR_VERSION 0)
set(CMAKE_MINOR_VERSION 1)
set(CMAKE_PATCH_VERSION 0)

set(BULL_ARCHIVE_INSTALL_PATH "lib")
set(BULL_LIBRARY_INSTALL_PATH "lib")
set(BULL_RUNTIME_INSTALL_PATH "bin")