set(CMAKE_CXX_STANDART 14)
set(CMAKE_CXX_FLAGS "-static")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "bin/${CMAKE_BUILD_TYPE}")

set(BULL_ROOT ${CMAKE_CURRENT_SOURCE_DIR})

set(CMAKE_MAJOR_VERSION 0)
set(CMAKE_MINOR_VERSION 1)
set(CMAKE_PATCH_VERSION 0)