#ifndef BULL_RENDER_CONTEXT_GLX_GLXCONTEXTNOERROR_HPP
#define BULL_RENDER_CONTEXT_GLX_GLXCONTEXTNOERROR_HPP

#include <Bull/Core/Support/Xlib/Xlib.hpp>

#include <Bull/Render/Context/ExtensionsLoader.hpp>

#define GLX_CONTEXT_OPENGL_NO_ERROR_ARB 0x31B3

#endif // BULL_RENDER_CONTEXT_GLX_GLXCONTEXTNOERROR_HPP
